"""AppxBlockMap generation (64 KiB SHA-256 blocks)."""

from __future__ import annotations

import base64
import hashlib
import os
import struct
import zlib
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

BLOCK_SIZE = 64 * 1024
HASH_METHOD = "http://www.w3.org/2001/04/xmlenc#sha256"
NS = "http://schemas.microsoft.com/appx/2010/blockmap"

# Files generated by the packer; never read from the layout as payload.
SKIP_NAMES = frozenset(
    {
        "[Content_Types].xml",
        "AppxBlockMap.xml",
        "AppxSignature.p7x",
        "AppxMetadata\\CodeIntegrity.cat",
    }
)


@dataclass(frozen=True)
class FileBlocks:
    """One <File> entry: hashes over uncompressed blocks, sizes over compressed ones.

    `compressed_sizes` is None for stored parts, where the format omits
    Block/@Size entirely.
    """

    name: str
    size: int
    block_hashes: Sequence[bytes]
    compressed_sizes: Sequence[int] | None = None


def package_path(rel: Path) -> str:
    return rel.as_posix().lstrip("/").replace("/", "\\")


def hash_file_blocks(data: bytes) -> tuple[list[bytes], list[int]]:
    """SHA-256 over each uncompressed 64 KiB block.

    An empty file has no blocks at all — `<File Name="…" Size="0" LfhSize="…"/>`
    with no children, as produced by Microsoft's own packer.
    """
    hashes: list[bytes] = []
    sizes: list[int] = []
    offset = 0
    while offset < len(data):
        chunk = data[offset : offset + BLOCK_SIZE]
        hashes.append(hashlib.sha256(chunk).digest())
        sizes.append(len(chunk))
        offset += BLOCK_SIZE
    return hashes, sizes


def deflate_blocks(data: bytes, level: int = 6) -> tuple[bytes, list[int]]:
    """Deflate `data` one 64 KiB block at a time.

    Returns the raw deflate stream and the compressed length of each block.
    Z_FULL_FLUSH terminates every block so its compressed extent is known — that
    length is what Block/@Size reports. The final `flush()` emits a 2-byte
    end-of-stream marker belonging to no block, which is why the block sizes sum
    to slightly less than the entry's compressed size.
    """
    compressor = zlib.compressobj(level, zlib.DEFLATED, -zlib.MAX_WBITS)
    stream = bytearray()
    sizes: list[int] = []
    for offset in range(0, len(data), BLOCK_SIZE):
        block = compressor.compress(data[offset : offset + BLOCK_SIZE])
        block += compressor.flush(zlib.Z_FULL_FLUSH)
        stream += block
        sizes.append(len(block))
    stream += compressor.flush()
    return bytes(stream), sizes


def zip_local_header_size(name_utf8: bytes, extra: bytes = b"") -> int:
    return 30 + len(name_utf8) + len(extra)


LFH_SIGNATURE = 0x04034B50
LFH_STRUCT = "<IHHHHHIIIHH"


@dataclass(frozen=True)
class LocalHeader:
    """A ZIP local file header as actually written to the archive."""

    name: bytes
    flag_bits: int
    size: int  # 30 + name length + extra length, i.e. the blockmap's LfhSize
    extra_len: int


def read_local_header(archive: bytes, offset: int) -> LocalHeader:
    """Parse the local file header at `offset` in a raw ZIP archive.

    Used to check declared LfhSize against reality: `zip_local_header_size`
    assumes no extra fields, and nothing in `zipfile` guarantees that.
    """
    fields = struct.unpack(LFH_STRUCT, archive[offset : offset + 30])
    sig, _ver, flag, _comp, _time, _date, _crc, _csize, _size, name_len, extra_len = (
        fields
    )
    if sig != LFH_SIGNATURE:
        raise ValueError(f"no local file header at offset {offset}")
    return LocalHeader(
        name=archive[offset + 30 : offset + 30 + name_len],
        flag_bits=flag,
        size=30 + name_len + extra_len,
        extra_len=extra_len,
    )


def collect_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for dirpath, _, filenames in os.walk(root):
        for fn in filenames:
            p = Path(dirpath) / fn
            if p.is_symlink():
                raise ValueError(f"layout contains a symlink: {p.relative_to(root)}")
            name = package_path(p.relative_to(root))
            if name in SKIP_NAMES:
                continue
            files.append(p)
    files.sort(key=lambda p: package_path(p.relative_to(root)).lower())
    return files


@dataclass(frozen=True)
class PreparedFile:
    """A payload file ready to be written: blockmap entry plus archive bytes."""

    blocks: FileBlocks
    payload: bytes  # what goes into the archive (deflated or verbatim)
    deflated: bool


def prepare_file(name: str, data: bytes, level: int = 6) -> PreparedFile:
    """Hash and compress one payload file.

    Deflate is used only when it actually pays off; otherwise the part is stored
    and Block/@Size is omitted, matching what Microsoft's packer does for
    already-compressed assets.
    """
    hashes, _ = hash_file_blocks(data)
    stream, compressed_sizes = deflate_blocks(data, level)

    if data and len(stream) < len(data):
        return PreparedFile(
            blocks=FileBlocks(name, len(data), hashes, compressed_sizes),
            payload=stream,
            deflated=True,
        )
    return PreparedFile(
        blocks=FileBlocks(name, len(data), hashes, None),
        payload=data,
        deflated=False,
    )


def _xml_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def render_blockmap_xml(entries: Sequence[FileBlocks], lfh_sizes: dict) -> bytes:
    lines = [
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
        f'<BlockMap xmlns="{NS}" HashMethod="{HASH_METHOD}">',
    ]
    for e in entries:
        lfh = lfh_sizes[e.name]
        head = f'  <File Name="{_xml_escape(e.name)}" Size="{e.size}" LfhSize="{lfh}"'
        if not e.block_hashes:  # empty file: no blocks at all
            lines.append(head + "/>")
            continue

        lines.append(head + ">")
        for i, h in enumerate(e.block_hashes):
            b64 = base64.b64encode(h).decode("ascii")
            if e.compressed_sizes is None:  # stored part: no compressed length
                lines.append(f'    <Block Hash="{b64}"/>')
            else:
                lines.append(
                    f'    <Block Hash="{b64}" Size="{e.compressed_sizes[i]}"/>'
                )
        lines.append("  </File>")
    lines.append("</BlockMap>")
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")


def content_types_xml(package_paths: Sequence[str]) -> bytes:
    defaults = {
        "xml": "application/vnd.ms-appx.manifest+xml",
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "json": "application/json",
        "txt": "text/plain",
        "dll": "application/x-msdownload",
        "exe": "application/x-msdownload",
        "winmd": "application/octet-stream",
        "p7x": "application/vnd.ms-appx.signature",
    }
    for p in package_paths:
        ext = Path(p.replace("\\", "/")).suffix.lstrip(".").lower()
        if ext and ext not in defaults:
            defaults[ext] = "application/octet-stream"

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">',
    ]
    for ext, ctype in sorted(defaults.items()):
        lines.append(f'  <Default Extension="{ext}" ContentType="{ctype}"/>')
    lines.append(
        '  <Override PartName="/AppxManifest.xml" '
        'ContentType="application/vnd.ms-appx.manifest+xml"/>'
    )
    lines.append(
        '  <Override PartName="/AppxBlockMap.xml" '
        'ContentType="application/vnd.ms-appx.blockmap+xml"/>'
    )
    lines.append(
        '  <Override PartName="/AppxSignature.p7x" '
        'ContentType="application/vnd.ms-appx.signature"/>'
    )
    lines.append("</Types>")
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")
