"""AppxBlockMap generation (64 KiB SHA-256 blocks)."""

from __future__ import annotations

import base64
import hashlib
import os
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

BLOCK_SIZE = 64 * 1024
HASH_METHOD = "http://www.w3.org/2001/04/xmlenc#sha256"
NS = "http://schemas.microsoft.com/appx/2010/blockmap"

# Files generated by the packer; never read from the layout as payload.
SKIP_NAMES = frozenset(
    {
        "[Content_Types].xml",
        "AppxBlockMap.xml",
        "AppxSignature.p7x",
        "AppxMetadata\\CodeIntegrity.cat",
    }
)


@dataclass(frozen=True)
class FileBlocks:
    name: str
    size: int
    block_hashes: Sequence[bytes]
    block_sizes: Sequence[int]


def package_path(rel: Path) -> str:
    return rel.as_posix().lstrip("/").replace("/", "\\")


def hash_file_blocks(data: bytes) -> Tuple[List[bytes], List[int]]:
    hashes: List[bytes] = []
    sizes: List[int] = []
    if not data:
        hashes.append(hashlib.sha256(b"").digest())
        sizes.append(0)
        return hashes, sizes
    offset = 0
    while offset < len(data):
        chunk = data[offset : offset + BLOCK_SIZE]
        hashes.append(hashlib.sha256(chunk).digest())
        sizes.append(len(chunk))
        offset += BLOCK_SIZE
    return hashes, sizes


def zip_local_header_size(name_utf8: bytes, extra: bytes = b"") -> int:
    return 30 + len(name_utf8) + len(extra)


LFH_SIGNATURE = 0x04034B50
LFH_STRUCT = "<IHHHHHIIIHH"


@dataclass(frozen=True)
class LocalHeader:
    """A ZIP local file header as actually written to the archive."""

    name: bytes
    flag_bits: int
    size: int  # 30 + name length + extra length, i.e. the blockmap's LfhSize
    extra_len: int


def read_local_header(archive: bytes, offset: int) -> LocalHeader:
    """Parse the local file header at `offset` in a raw ZIP archive.

    Used to check declared LfhSize against reality: `zip_local_header_size`
    assumes no extra fields, and nothing in `zipfile` guarantees that.
    """
    fields = struct.unpack(LFH_STRUCT, archive[offset : offset + 30])
    sig, _ver, flag, _comp, _time, _date, _crc, _csize, _size, name_len, extra_len = (
        fields
    )
    if sig != LFH_SIGNATURE:
        raise ValueError(f"no local file header at offset {offset}")
    return LocalHeader(
        name=archive[offset + 30 : offset + 30 + name_len],
        flag_bits=flag,
        size=30 + name_len + extra_len,
        extra_len=extra_len,
    )


def collect_files(root: Path) -> List[Path]:
    files: List[Path] = []
    for dirpath, _, filenames in os.walk(root):
        for fn in filenames:
            p = Path(dirpath) / fn
            name = package_path(p.relative_to(root))
            if name in SKIP_NAMES:
                continue
            files.append(p)
    files.sort(key=lambda p: package_path(p.relative_to(root)).lower())
    return files


def build_file_blocks(root: Path, files: Iterable[Path]) -> List[FileBlocks]:
    out: List[FileBlocks] = []
    for p in files:
        data = p.read_bytes()
        hashes, sizes = hash_file_blocks(data)
        out.append(
            FileBlocks(
                name=package_path(p.relative_to(root)),
                size=len(data),
                block_hashes=hashes,
                block_sizes=sizes,
            )
        )
    return out


def _xml_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def render_blockmap_xml(entries: Sequence[FileBlocks], lfh_sizes: dict) -> bytes:
    lines = [
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
        f'<BlockMap xmlns="{NS}" HashMethod="{HASH_METHOD}">',
    ]
    for e in entries:
        lfh = lfh_sizes[e.name]
        lines.append(
            f'  <File Name="{_xml_escape(e.name)}" Size="{e.size}" LfhSize="{lfh}">'
        )
        for h, sz in zip(e.block_hashes, e.block_sizes):
            b64 = base64.b64encode(h).decode("ascii")
            if sz == BLOCK_SIZE:
                lines.append(f'    <Block Hash="{b64}"/>')
            else:
                lines.append(f'    <Block Hash="{b64}" Size="{sz}"/>')
        lines.append("  </File>")
    lines.append("</BlockMap>")
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")


def content_types_xml(package_paths: Sequence[str]) -> bytes:
    defaults = {
        "xml": "application/vnd.ms-appx.manifest+xml",
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "json": "application/json",
        "txt": "text/plain",
        "dll": "application/x-msdownload",
        "exe": "application/x-msdownload",
        "winmd": "application/octet-stream",
        "p7x": "application/vnd.ms-appx.signature",
    }
    for p in package_paths:
        ext = Path(p.replace("\\", "/")).suffix.lstrip(".").lower()
        if ext and ext not in defaults:
            defaults[ext] = "application/octet-stream"

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">',
    ]
    for ext, ctype in sorted(defaults.items()):
        lines.append(f'  <Default Extension="{ext}" ContentType="{ctype}"/>')
    lines.append(
        '  <Override PartName="/AppxManifest.xml" '
        'ContentType="application/vnd.ms-appx.manifest+xml"/>'
    )
    lines.append(
        '  <Override PartName="/AppxBlockMap.xml" '
        'ContentType="application/vnd.ms-appx.blockmap+xml"/>'
    )
    lines.append(
        '  <Override PartName="/AppxSignature.p7x" '
        'ContentType="application/vnd.ms-appx.signature"/>'
    )
    lines.append("</Types>")
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")
